apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuxt3
  namespace: nuxt3
  labels:
    app: nuxt3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nuxt3
  template:
    metadata:
      labels:
        app: nuxt3
    spec:
      containers:
      - name: nuxt3
        image: nuxt3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
      restartPolicy: Always
